---
sidebar: sidebar 
permalink: concept-licensing.html 
keywords: 'freemium, professional, essentials, licensing, licenses, cloud volumes ontap charging, cloud volumes ontap licenses, cloud volumes ontap licensing, cvo licenses, cvo licensing, byol, bring your own license, paygo, pay as you go, keystone flex, keystone, cloud backup, digital wallet, bluexp license conversion for node based, license end of support (EOS) node-based, end of availability (EOA) of node-based' 
summary: 'Plusieurs options de licence sont disponibles pour Cloud Volumes ONTAP. Chacune d"elles vous permet de choisir une configuration qui répond à vos besoins.' 
---
= Licences pour Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Plusieurs options de licence sont disponibles pour Cloud Volumes ONTAP. Chacune d'elles vous permet de choisir un modèle de consommation adapté à vos besoins.



== Présentation des licences

Des options de licence sont disponibles pour les nouveaux clients :

Licences basées sur la capacité:: Payez plusieurs systèmes Cloud Volumes ONTAP sur votre compte NetApp grâce à la capacité provisionnée. Inclut la possibilité d'acheter des services de données cloud supplémentaires. Pour plus d'informations sur les modèles de consommation dans les licences basées sur la capacité, reportez-vous link:concept-licensing-charging.html["En savoir plus sur les licences basées sur la capacité"]à la section .
Abonnement Keystone:: Service d'abonnement flexible avec paiement à l'utilisation offrant une expérience de cloud hybride fluide pour les paires haute disponibilité.


Les sections suivantes fournissent plus de détails sur chacune de ces options.


NOTE: L'assistance n'est pas disponible pour l'utilisation des fonctions sous licence sans licence.



== Licences basées sur la capacité

Les packs de licence basés sur la capacité vous permettent de payer le Cloud Volumes ONTAP par To de capacité. La licence est associée à votre compte NetApp et vous permet de facturer plusieurs systèmes par rapport à la licence, tant que la capacité disponible par le biais de la licence est suffisante.

Par exemple, vous pouvez acheter une seule licence de 20 Tio, déployer quatre systèmes Cloud Volumes ONTAP puis allouer un volume de 5 Tio à chaque système, pour un total de 20 Tio. La capacité est disponible pour les volumes de chaque système Cloud Volumes ONTAP déployé sur ce compte.

Une licence basée sur la capacité est disponible sous la forme d'un _package_. Lorsque vous déployez un système Cloud Volumes ONTAP, vous avez le choix entre plusieurs packages de licences en fonction des besoins de votre entreprise.


NOTE: Même si l'utilisation et les mesures réelles des produits et services gérés dans BlueXP sont toujours calculés en Gio et en Tio, les termes Go/Gio et To/Tio sont utilisés de manière interchangeable. Elles figurent dans les offres Cloud Marketplace, les devis, les descriptions des offres ainsi que d'autres documents justificatifs.



=== Packs

Les packages basés sur la capacité suivants sont disponibles pour Cloud Volumes ONTAP. Pour plus d'informations sur les packages de licences basés sur la capacité, reportez-vous à la section link:concept-licensing-charging.html["En savoir plus sur les licences basées sur la capacité"].

Pour obtenir la liste des types de VM pris en charge avec les packages basés sur la capacité suivants, reportez-vous à :

ifdef::azure[]

* link:https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-azure.html["Configurations prises en charge dans Azure"^]


endif::azure[]

ifdef::gcp[]

* link:https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html["Configurations prises en charge dans Google Cloud"^]


endif::gcp[]



==== Fréemium

Fournit toutes les fonctionnalités Cloud Volumes ONTAP gratuitement auprès de NetApp (frais des fournisseurs cloud toujours applicables).

* Aucune licence ni contrat n'est nécessaire.
* L'assistance de NetApp n'est pas incluse.
* Votre système Cloud Volumes ONTAP est limité à 500 Gio de capacité provisionnée.
* Vous pouvez utiliser jusqu'à 10 systèmes Cloud Volumes ONTAP avec l'offre « Freemium » par compte NetApp, quel que soit le fournisseur de cloud.
* Si la capacité provisionnée d'un système Cloud Volumes ONTAP dépasse 500 Gio, BlueXP convertit le système en package Essentials.
+
Dès qu'un système est converti en package Essentials, le link:concept-licensing-charging.html#minimum-charge["charge minimale"] s'applique.

+
Tous les autres systèmes dont la capacité provisionnée est inférieure à 500 Gio restent sur « Freemium » (tant qu'ils ont été déployés à l'aide de l'offre Freemium).





==== Points essentiels

Vous pouvez payer par capacité dans plusieurs configurations différentes :

* Choisissez votre configuration Cloud Volumes ONTAP :
+
** Un seul nœud ou un système HA
** Stockage basé sur des fichiers ou des blocs ou données secondaires pour la reprise après incident


* Ajoutez des services de données cloud de NetApp à vos frais supplémentaires




==== Optimisé

Payez séparément la capacité provisionnée et les opérations d'E/S.

* Cloud Volumes ONTAP à un seul nœud ou haute disponibilité
* La facturation se base sur deux éléments de coûts : le stockage et l'utilisation (E/S).
+
Vous ne serez pas facturé pour les E/S liées à la réplication de données (SnapMirror), aux sauvegardes (SnapVault) ou à NDMP.



ifdef::azure[]

* Disponible sur Azure Marketplace comme offre de paiement à l'utilisation ou comme contrat annuel


endif::azure[]

ifdef::gcp[]

* Disponible dans Google Cloud Marketplace comme offre de paiement à l'utilisation ou comme contrat annuel


endif::gcp[]

* Ajoutez des services de données cloud de NetApp à vos frais supplémentaires




==== Professionnel

Payez par capacité pour tout type de configuration Cloud Volumes ONTAP avec des sauvegardes illimitées.

* Licence pour toute configuration Cloud Volumes ONTAP
+
Un seul nœud ou haute disponibilité avec chargement de la capacité pour les volumes primaires et secondaires au même rythme

* Inclut des sauvegardes de volume illimitées avec la sauvegarde et la restauration BlueXP, mais uniquement pour les systèmes Cloud Volumes ONTAP qui utilisent l'offre professionnelle.
+

NOTE: Vous devez souscrire un abonnement PAYGO pour la sauvegarde et la restauration BlueXP . Cependant, vous n'aurez aucun frais à payer pour l'utilisation de ce service. Pour plus d'informations sur la configuration des licences pour la sauvegarde et la restauration BlueXP , reportez-vous https://docs.netapp.com/us-en/bluexp-backup-recovery/task-licensing-cloud-backup.html["Configurez les licences pour la sauvegarde et la restauration BlueXP"^] à la section.

* Ajoutez des services de données cloud de NetApp à vos frais supplémentaires




=== Disponibilité des licences basées sur la capacité

Pour assurer la disponibilité des licences PAYGO et BYOL pour les systèmes Cloud Volumes ONTAP, BlueXP  Connector doit être opérationnel. Pour plus d'informations, reportez-vous https://docs.netapp.com/us-en/bluexp-setup-admin/concept-connectors.html#impact-on-cloud-volumes-ontap["En savoir plus sur les connecteurs"^]à .



=== Comment démarrer

Découvrez comment utiliser les licences basées sur la capacité :

ifdef::aws[]

* link:task-set-up-licensing-aws.html["Configuration des licences pour Cloud Volumes ONTAP dans AWS"]


endif::aws[]

ifdef::azure[]

* link:task-set-up-licensing-azure.html["Configuration des licences pour Cloud Volumes ONTAP dans Azure"]


endif::azure[]

ifdef::gcp[]

* link:task-set-up-licensing-google.html["Configurez la licence pour Cloud Volumes ONTAP dans Google Cloud"]


endif::gcp[]



== Abonnement Keystone

Service basé sur un abonnement avec paiement à l'utilisation qui offre une expérience de cloud hybride transparente, pour les modèles de consommation OpEx, qui préfèrent les CapEx ou les crédits sur investissement en amont.

Le coût est calculé en fonction de la taille de votre capacité allouée pour une ou plusieurs paires Cloud Volumes ONTAP HA dans votre abonnement Keystone.

La capacité provisionnée pour chaque volume est agrégée et comparée à la capacité allouée dans votre abonnement Keystone régulièrement, et tout dépassement est facturé en rafale dans votre abonnement Keystone.

link:https://docs.netapp.com/us-en/keystone-staas/index.html["En savoir plus sur NetApp Keystone"^].



=== Configurations compatibles

Les abonnements Keystone sont pris en charge avec les paires haute disponibilité. Cette option de licence n'est pas prise en charge pour le moment avec des systèmes à un seul nœud.



=== Limite de capacité

Chaque système Cloud Volumes ONTAP peut atteindre jusqu'à 2 Pio de capacité maximale grâce à des disques et à une hiérarchisation sur le stockage objet.



=== Comment démarrer

Découvrez comment vous lancer avec un abonnement Keystone :

ifdef::aws[]

* link:task-set-up-licensing-aws.html["Configuration des licences pour Cloud Volumes ONTAP dans AWS"]


endif::aws[]

ifdef::azure[]

* link:task-set-up-licensing-azure.html["Configuration des licences pour Cloud Volumes ONTAP dans Azure"]


endif::azure[]

ifdef::gcp[]

* link:task-set-up-licensing-google.html["Configurez la licence pour Cloud Volumes ONTAP dans Google Cloud"]


endif::gcp[]



== Licence basée sur les nœuds

La licence basée sur les nœuds est le modèle de licence de la génération précédente qui vous permet d'obtenir une licence Cloud Volumes ONTAP par nœud. Ce modèle de licence n'est pas disponible pour les nouveaux clients. Le chargement par nœud a été remplacé par les méthodes de charge par capacité décrites ci-dessus.

NetApp a prévu la fin de disponibilité et la fin de prise en charge des licences basées sur les nœuds. Après la fin de disponibilité et l'EOS, les licences basées sur les nœuds devront être converties en licences basées sur la capacité.

Pour plus d'informations, reportez-vous à https://mysupport.netapp.com/info/communications/CPC-00589.html["Communiqué à la clientèle : CPC-00589"^]la .



=== Fin de disponibilité des licences basées sur les nœuds

Depuis le 11 novembre 2024, la disponibilité limitée des licences basées sur les nœuds a pris fin. La prise en charge des licences basées sur les nœuds prend fin le 31 décembre 2024.

Si vous disposez d'un contrat basé sur les nœuds valide qui s'étend au-delà de la date de fin de disponibilité, vous pouvez continuer à utiliser la licence jusqu'à l'expiration du contrat. Une fois le contrat expiré, il sera nécessaire de passer au modèle de licence basé sur la capacité. Si vous n'avez pas de contrat à long terme pour un nœud Cloud Volumes ONTAP, il est important de planifier votre conversion avant la date de fin de support.

Pour en savoir plus sur chaque type de licence et sur l'impact de la fin de disponibilité sur ce type de licence, consultez ce tableau :

[cols="2*"]
|===
| Type de licence | Impact après la fin de disponibilité 


 a| 
Licence valide basée sur les nœuds achetée via BYOL (Bring Your Own License)
 a| 
La licence reste valide jusqu'à son expiration. Les licences basées sur des nœuds déjà utilisées peuvent être utilisées pour déployer de nouveaux systèmes Cloud Volumes ONTAP.



 a| 
Licence basée sur les nœuds expirée, achetée via BYOL
 a| 
Vous ne serez pas autorisé à déployer de nouveaux systèmes Cloud Volumes ONTAP à l'aide de cette licence. Les systèmes existants peuvent continuer à fonctionner, mais vous ne recevrez aucune assistance ni mise à jour pour vos systèmes après la date de fin de support.



 a| 
Licence basée sur les nœuds valide avec abonnement PAYGO
 a| 
Vous cesserez de recevoir le support NetApp après la date de fin de support, jusqu'à ce que vous ayez opté pour une licence basée sur la capacité.

|===
.Exclusions
NetApp reconnaît que certaines situations nécessitent une attention particulière, et la fin de disponibilité et la fin de commercialisation des licences basées sur des nœuds ne s'appliquent pas aux cas suivants :

* Aux États-Unis
* Déploiements en mode privé
* Déploiements de Cloud Volumes ONTAP dans AWS dans la région chinoise


Pour ces scénarios particuliers, NetApp offre un support afin de répondre aux exigences uniques en matière de licence, dans le respect des obligations contractuelles et des besoins opérationnels.


NOTE: Même dans ces scénarios, les nouvelles licences basées sur les nœuds et les renouvellements de licences sont valables pendant un an maximum à compter de la date d'approbation.



== Conversion de licence

BlueXP  permet de convertir en toute transparence les licences basées sur les nœuds en fonction de la capacité via l'outil de conversion des licences. Pour plus d'informations sur la fin de disponibilité des licences basées sur les nœuds, reportez-vous à link:concept-licensing.html#end-of-availability-of-node-based-licenses["Fin de disponibilité des licences basées sur les nœuds"]la section .

Avant la transition, il est bon de vous familiariser avec la différence entre les deux modèles de licence. La licence basée sur les nœuds inclut une capacité fixe pour chaque instance ONTAP, ce qui peut limiter la flexibilité. Les licences basées sur la capacité, quant à elles, permettent de partager un pool de stockage entre plusieurs instances. Résultat : une flexibilité accrue, une utilisation optimisée des ressources et une réduction des pénalités financières potentielles lors de la redistribution des charges de travail. La charge basée sur la capacité s'adapte en toute transparence à l'évolution des besoins en stockage.

Pour savoir comment effectuer cette conversion, reportez-vous à la section link:task-convert-node-capacity.html["Il convertit une licence Cloud Volumes ONTAP basée sur les nœuds en licence basée sur la capacité"].


NOTE: La conversion d'un système de licences basées sur la capacité en licences basées sur des nœuds n'est pas prise en charge.
