---
settings:
  name: Cloud Volumes ONTAP
  harmony_integration: maestro
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  filter:
    label: Ou du fournisseur cloud
    default: Tous les fournisseurs cloud
    options:
    - name: Amazon Web Services
      alias: AWS
      id: aws
    - name: Google Cloud
      alias: Google Cloud
      id: gcp
    - name: Microsoft Azure
      alias: Azure
      id: azure
  langs: fr-fr,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,it-it
sidebar:
  entries:
  - title: Documentation Cloud Volumes ONTAP
    url: "/index.html"
  - title: Notes de mise à jour
    entries:
    - title: Quoi de neuf
      url: "/whats-new.html"
    - title: Limites connues
      url: "/reference-limitations.html"
    - title: Notes de version de Cloud Volumes ONTAP
      url: "/whats-new-ontap.html"
  - title: Commencez
    entries:
    - title: Découvrez Cloud Volumes ONTAP
      url: "/concept-overview-cvo.html"
    - title: Versions prises en charge pour les nouveaux déploiements
      url: "/reference-versions.html"
    - title: Lancez-vous dans Amazon Web Services
      flavor: aws
      entries:
      - title: Démarrage rapide
        url: "/task-getting-started-aws.html"
      - title: Planification de la configuration
        url: "/task-planning-your-config.html"
      - title: Configurez votre réseau
        entries:
        - title: Configuration réseau requise
          url: "/reference-networking-aws.html"
        - title: Configuration d'une passerelle de transit AWS
          url: "/task-setting-up-transit-gateway.html"
        - title: Déploiement d'une paire haute disponibilité dans un sous-réseau partagé
          url: "/task-deploy-aws-shared-vpc.html"
        - title: Règles de groupe de sécurité pour AWS
          url: "/reference-security-groups.html"
      - title: Configuration du KMS AWS
        url: "/task-setting-up-kms.html"
      - title: Configurer les rôles IAM
        url: "/task-set-up-iam-roles.html"
      - title: Configuration des licences
        url: "/task-set-up-licensing-aws.html"
      - title: Lancement d'Cloud Volumes ONTAP dans AWS
        url: "/task-deploying-otc-aws.html"
      - title: Lancez-vous dans AWS C2S
        url: "/task-getting-started-aws-c2s.html"
    - title: Commencez avec Microsoft Azure
      flavor: azure
      entries:
      - title: Démarrage rapide
        url: "/task-getting-started-azure.html"
      - title: Planification de la configuration
        url: "/task-planning-your-config-azure.html"
      - title: Configurez votre réseau
        url: "/reference-networking-azure.html"
      - title: Configurez le chiffrement à l'aide de votre clé
        url: "/task-set-up-azure-encryption.html"
      - title: Configuration des licences
        url: "/task-set-up-licensing-azure.html"
      - title: Activer le mode haute disponibilité
        url: "/task-azure-high-availability-mode.html"
      - title: Lancez Cloud Volumes ONTAP dans Azure
        url: "/task-deploying-otc-azure.html"
    - title: Lancez-vous dans Google Cloud
      flavor: gcp
      entries:
      - title: Démarrage rapide
        url: "/task-getting-started-gcp.html"
      - title: Planification de la configuration
        url: "/task-planning-your-config-gcp.html"
      - title: Configurez votre réseau
        url: "/reference-networking-gcp.html"
      - title: Planifiez les contrôles de service VPC
        url: "/reference-vpc-service-controls-gcp.html"
      - title: Créez un compte de service
        url: "/task-creating-gcp-service-account.html"
      - title: Utilisez des clés de chiffrement gérées par le client
        url: "/task-setting-up-gcp-encryption.html"
      - title: Configuration des licences
        url: "/task-set-up-licensing-google.html"
      - title: Lancez Cloud Volumes ONTAP dans Google Cloud
        url: "/task-deploying-gcp.html"
      - title: Vérification des images Google Cloud Platform
        entries:
        - title: Présentation
          url: "/concept-gcp-image-verification.html"
        - title: Convertir l'image au format brut sur GCP
          url: "/task-gcp-convert-image-raw.html"
        - title: Vérification de la signature d'image
          entries:
          - title: Vérifiez les images signées GCP
            url: "/concept-gcp-verify-signed-image.html"
          - title: Vérifiez le contenu à l'aide d'OpenSSL
            url: "/task-verify-openssl-gcp.html"
  - title: Utiliser Cloud Volumes ONTAP
    entries:
    - title: Gestion des licences
      entries:
      - title: Gestion des licences basées sur la capacité
        url: "/task-manage-capacity-licenses.html"
      - title: Gestion des abonnements Keystone
        url: "/task-manage-keystone.html"
      - title: Gestion des licences basées sur des nœuds
        url: "/task-manage-node-licenses.html"
    - title: Administration des volumes et des LUN
      entries:
      - title: Créer des volumes
        url: "/task-create-volumes.html"
      - title: Gérer les volumes existants
        url: "/task-manage-volumes.html"
      - title: Transférez les données inactives vers le stockage objet
        url: "/task-tiering.html"
      - title: Connectez une LUN à un hôte
        url: "/task-connect-lun.html"
      - title: Accélérez l'accès aux données avec FlexCache
        url: "/task-accelerate-data-access.html"
    - title: Administration d'agrégats
      entries:
      - title: Créer des agrégats
        url: "/task-create-aggregates.html"
      - title: Gérez les agrégats existants
        url: "/task-manage-aggregates.html"
      - title: Gérer les paramètres de capacité
        url: "/task-manage-capacity-settings.html"
    - title: Administration des machines virtuelles de stockage
      entries:
      - title: Compatible avec les machines virtuelles de stockage dans BlueXP
        url: "/task-managing-svms.html"
      - title: Créez des machines virtuelles de stockage dans AWS
        flavor: aws
        url: "/task-managing-svms-aws.html"
      - title: Créez des machines virtuelles de stockage dans Azure
        flavor: azure
        url: "/task-managing-svms-azure.html"
      - title: Création de machines virtuelles de stockage dans Google Cloud
        flavor: gcp
        url: "/task-managing-svms-gcp.html"
    - title: Sécurité et chiffrement des données
      entries:
      - title: Chiffrement des volumes avec le chiffrement NetApp
        url: "/task-encrypting-volumes.html"
      - title: Gérez les clés avec Azure Key Vault
        flavor: azure
        url: "/task-azure-key-vault.html"
      - title: Gérez les clés via Google Cloud KMS
        flavor: gcp
        url: "/task-google-key-manager.html"
      - title: Améliorez la protection par ransomware
        url: "/task-protecting-ransomware.html"
    - title: Administration du système
      entries:
      - title: Mettez à niveau Cloud Volumes ONTAP
        url: "/task-updating-ontap-cloud.html"
      - title: Enregistrez les systèmes avec paiement à l'utilisation
        url: "/task-registering.html"
      - title: Arrêter et démarrer un système
        url: "/task-managing-state.html"
      - title: Synchroniser l'heure du système
        url: "/task-sync-time.html"
      - title: Modifier la vitesse d'écriture du système
        url: "/task-modify-write-speed.html"
      - title: Modifier le mot de passe système
        url: "/task-change-password.html"
      - title: Ajouter, supprimer ou supprimer des systèmes
        entries:
        - title: Ajouter un système existant
          url: "/task-adding-systems.html"
        - title: Supprimez un environnement de travail
          url: "/task-removing.html"
        - title: Supprimer un système
          url: "/task-deleting-working-env.html"
      - title: Administration AWS
        flavor: aws
        entries:
        - title: Modifiez le type d'instance EC2
          url: "/task-change-ec2-instance.html"
        - title: Modifier les tables de routage pour les paires haute disponibilité
          url: "/task-change-route-tables.html"
        - title: Contrôle des coûts AWS
          url: "/task-monitoring-costs.html"
        - title: Configurer la création d'un groupe de placement
          url: task-configure-placement-group-failure-aws.html
      - title: Administration d'Azure
        flavor: azure
        entries:
        - title: Modifier le type de machine virtuelle Azure
          url: "/task-change-azure-vm.html"
        - title: Remplacement des verrouillages CIFS
          url: "/task-overriding-cifs-locks.html"
        - title: Utilisez une liaison privée Azure ou des terminaux de service
          url: "/task-enabling-private-link.html"
        - title: Déplacer des groupes de ressources
          url: "/task-moving-resource-groups-azure.html"
      - title: Administration Google Cloud
        flavor: gcp
        entries:
        - title: Modifier le type de machine
          url: "/task-change-gcp-machine.html"
      - title: Administration depuis System Manager
        url: "/task-administer-advanced-view.html"
      - title: Administration depuis l'interface de ligne de commandes
        url: "/task-connecting-to-otc.html"
    - title: État de santé du système et événements
      entries:
      - title: Vérifiez la configuration de AutoSupport
        url: "/task-verify-autosupport.html"
      - title: Configurer EMS
        url: "/task-configure-ems.html"
  - title: Concepts
    entries:
    - title: Licences
      url: "/concept-licensing.html"
    - title: Stockage
      entries:
      - title: Protocoles clients
        url: "/concept-client-protocols.html"
      - title: Disques et agrégats
        url: "/concept-storage.html"
      - title: Volumes flexibles dans AWS
        flavor: aws
        url: "/concept-aws-elastic-volumes.html"
      - title: Tiering des données
        url: "/concept-data-tiering.html"
      - title: Gestion du stockage
        url: "/concept-storage-management.html"
      - title: Vitesse d'écriture
        url: "/concept-write-speed.html"
      - title: Flash cache
        url: "/concept-flash-cache.html"
      - title: Stockage WORM
        url: "/concept-worm.html"
    - title: Paires haute disponibilité
      entries:
      - title: Paires HA dans AWS
        flavor: aws
        url: "/concept-ha.html"
      - title: Paires HA dans Azure
        flavor: azure
        url: "/concept-ha-azure.html"
      - title: Paires HA dans GCP
        flavor: gcp
        url: "/concept-ha-google-cloud.html"
      - title: Actions lors de l'acquisition du stockage
        url: "/concept-degraded-ha-pair.html"
    - title: Sécurité
      url: "/concept-security.html"
    - title: Performance
      url: "/concept-performance.html"
    - title: Gestion du modèle BYOL basé sur des nœuds
      url: "/concept-license-management.html"
    - title: Conseiller digital AutoSupport et Active IQ
      url: "/concept-active-iq.html"
    - title: Configurations par défaut
      url: "/reference-default-configs.html"
  - title: Connaissances et support
    entries:
    - title: S'inscrire pour obtenir de l'aide
      url: "/task-support-registration.html"
    - title: Obtenez de l'aide
      url: "/task-get-help.html"
  - title: Mentions légales
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Commencez
    links:
    - title: Découvrez Cloud Volumes ONTAP
      url: concept-overview-cvo.html
    - title: Démarrage rapide pour AWS
      url: task-getting-started-aws.html
      flavor: aws
    - title: Démarrage rapide pour Azure
      url: task-getting-started-azure.html
      flavor: azure
    - title: Démarrage rapide pour Google Cloud
      url: task-getting-started-gcp.html
      flavor: gcp
  - title: Licences
    links:
    - title: Présentation des licences
      url: concept-licensing.html
    - title: Gestion des licences basées sur la capacité
      url: task-manage-capacity-licenses.html
    - title: Licences Exchange non attribuées basées sur des nœuds
      url: task-manage-node-licenses.html#exchange-unassigned-node-based-licenses
    - title: Gestion des abonnements Keystone
      url: task-manage-keystone.html
  - title: Gestion du stockage
    links:
    - title: Créer des volumes
      url: task-create-volumes.html
    - title: Transférez les données inactives vers le stockage objet
      url: task-tiering.html
    - title: Accélérez l'accès aux données avec FlexCache
      url: task-accelerate-data-access.html
    - title: Configuration de l'hôte SAN ONTAP
      url: https://docs.netapp.com/us-en/ontap-sanhost
  - title: Administration du système
    links:
    - title: Mettez à niveau Cloud Volumes ONTAP
      url: task-updating-ontap-cloud.html
    - title: Arrêtez et démarrez Cloud Volumes ONTAP
      url: task-managing-state.html
  - title: Sécurité
    links:
    - title: Chiffrement des volumes avec le chiffrement NetApp
      url: task-encrypting-volumes.html
    - title: Améliorez la protection par ransomware
      url: task-protecting-ransomware.html
  - title: API
    links:
    - title: Présentation de l'API Cloud Volumes ONTAP
      url: https://docs.netapp.com/us-en/cloud-manager-automation/cm/overview.html
    - title: Préparez-vous à utiliser l'API
      url: https://docs.netapp.com/us-en/cloud-manager-automation/cm/prepare.html
    - title: Référence API
      url: https://docs.netapp.com/us-en/cloud-manager-automation/cm/api_ref_resources.html
  - title: Dépannage
    links:
    - title: Base de connaissances NetApp
      url: https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Cloud_Volumes_ONTAP_(CVO)
  - title: Référence
    links:
    - title: Configurations compatibles
      url: https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/index.html
    - title: Régions cloud prises en charge
      url: https://cloud.netapp.com/cloud-volumes-global-regions
    - title: Outils de calcul
      url: https://cloud.netapp.com/calculator-hub
  - title: Communauté sur les blogs
    links:
    - title: Communauté NetApp
      url: https://community.netapp.com/t5/Cloud-Volumes-ONTAP/bd-p/CloudVolumes
    - title: Blog du site Web BlueXP
      url: https://cloud.netapp.com/blog/topic/cloud-volumes-ontap
    - title: Webinaires sur le cloud
      url: https://cloud.netapp.com/events
product-family:
  name: BlueXP
  repo: cloud-manager-family
  sidebar_label: Toute la documentation BlueXP
