---
sidebar: sidebar 
permalink: reference-worm-snaplock.html 
keywords: WORM, SnapLock, Snapshot copies, 
summary: 'Vous pouvez créer des copies Snapshot inviolables de fichiers WORM (Write Once, Read Many) sur un système Cloud Volumes ONTAP et conserver les copies Snapshot sous forme non modifiée pendant une période de conservation spécifique.' 
---
= Créez des copies Snapshot inviolables de fichiers WORM sur Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez créer des copies Snapshot inviolables de fichiers WORM (Write Once, Read Many) sur un système Cloud Volumes ONTAP et conserver les copies Snapshot sous forme non modifiée pendant une période de conservation spécifique. Optimisée par la technologie SnapLock, cette fonctionnalité offre une couche supplémentaire de protection et de conformité des données.

.Avant de commencer
Assurez-vous que le volume que vous utilisez pour créer des copies Snapshot est un volume SnapLock. Pour plus d'informations sur l'activation de la protection SnapLock sur les volumes, reportez-vous au https://docs.netapp.com/us-en/ontap/snaplock/snaplock-config-overview-concept.html["Documentation ONTAP : configurez SnapLock"^].

.Étapes
. Créez des copies Snapshot à partir du volume SnapLock. Pour plus d'informations sur la création de copies Snapshot à l'aide de l'interface de ligne de commandes ou de System Manager, reportez-vous au https://docs.netapp.com/us-en/ontap/data-protection/manage-local-snapshot-copies-concept.html["Documentation ONTAP : présentation de la gestion des copies Snapshot locales"^] .
+
Les copies Snapshot héritent des propriétés WORM du volume, ce qui les rend inviolables. La technologie SnapLock sous-jacente protège le snapshot contre toute modification ou suppression jusqu'à ce que la période de conservation spécifiée soit écoulée.

. Vous pouvez modifier la période de conservation si vous devez modifier ces snapshots. Pour plus d'informations, reportez-vous au https://docs.netapp.com/us-en/ontap/snaplock/set-retention-period-task.html#set-the-default-retention-period["Documentation ONTAP : permet de définir la durée de conservation"^] .



NOTE: Même si une copie Snapshot est protégée pendant une période de conservation spécifique, un administrateur de cluster peut supprimer le volume source, dans la mesure où le stockage WORM dans Cloud Volumes ONTAP fonctionne selon un modèle d'« administrateur de stockage de confiance ». En outre, un administrateur cloud de confiance peut supprimer les données WORM en s'appuyant sur les ressources de stockage cloud.
