---
sidebar: sidebar 
permalink: task-getting-started-aws-c2s.html 
keywords: commercial cloud services, c2s, secret cloud, top secret cloud, aws secret region, BlueXP 
summary: 'Comme dans une région AWS standard, vous pouvez utiliser BlueXP dans les environnements de cloud secret AWS et Top Secret pour déployer Cloud Volumes ONTAP, qui fournit des fonctionnalités haute performance pour votre stockage cloud. Les régions AWS Secret Cloud et Top Secret Cloud sont des régions fermées spécifiques aux États-Unis Communauté de renseignement ; les instructions de cette page s"appliquent uniquement aux utilisateurs de la région du cloud secret AWS et du cloud secret supérieur.' 
---
= Déployez Cloud Volumes ONTAP dans le cloud secret AWS ou le cloud secret AWS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Comme pour une région AWS standard, vous pouvez utiliser BlueXP dans link:https://aws.amazon.com/federal/secret-cloud/["Cloud secret AWS"^] et po link:https://aws.amazon.com/federal/top-secret-cloud/["Le cloud le plus secret d'AWS"^] De déployer Cloud Volumes ONTAP, qui fournit des fonctionnalités de grande qualité pour votre stockage cloud. AWS Secret Cloud et Top Secret Cloud sont des régions fermées spécifiques aux États-Unis Communauté de renseignement ; les instructions de cette page s'appliquent uniquement aux utilisateurs de la région du cloud secret AWS et du cloud secret supérieur.

.Avant de commencer
Avant de commencer, consultez les versions prises en charge dans AWS Secret Cloud et Top Secret Cloud, et découvrez le mode privé dans BlueXP.

* Consultez les versions prises en charge suivantes dans AWS Secret Cloud et Top Secret Cloud :
+
** Cloud Volumes ONTAP 9.12.1 P2
** Version 3.9.32 du connecteur
+
Il s'agit du logiciel requis pour déployer et gérer Cloud Volumes ONTAP dans AWS. Vous vous connecterez à BlueXP à partir du logiciel installé sur l'instance de connecteur. Le site Web SaaS pour BlueXP n'est pas pris en charge dans AWS Secret Cloud et Top Secret Cloud.



* En savoir plus sur le mode privé
+
Dans AWS Secret Cloud et Top Secret Cloud, BlueXP fonctionne en _mode privé_. En mode privé, la couche SaaS de BlueXP n'est pas connectée. Les utilisateurs accèdent à BlueXP en local à partir de la console web disponible depuis le connecteur, et non depuis la couche SaaS.

+
Pour en savoir plus sur le fonctionnement du mode privé, reportez-vous à la section link:https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html#private-mode["Mode de déploiement privé BlueXP"^].





== Étape 1 : configuration du réseau

Configurez votre réseau AWS pour que Cloud Volumes ONTAP puisse fonctionner correctement.

.Étapes
. Choisissez le VPC et les sous-réseaux dans lesquels vous souhaitez lancer l'instance de connecteur et les instances Cloud Volumes ONTAP.
. Vérifiez que votre VPC et vos sous-réseaux prennent en charge la connectivité entre le connecteur et Cloud Volumes ONTAP.
. Configurez un terminal VPC sur le service S3.
+
Un point de terminaison VPC est requis si vous souhaitez transférer des données à froid de Cloud Volumes ONTAP vers un stockage objet économique.





== Étape 2 : configurer les autorisations

Configurez des stratégies et des rôles IAM qui fournissent au connecteur et à Cloud Volumes ONTAP les autorisations dont ils ont besoin pour effectuer des actions dans le cloud secret AWS ou le cloud top secret.

Vous avez besoin d'une politique IAM et d'un rôle IAM pour chacun des éléments suivants :

* L'instance de connecteur
* Instances Cloud Volumes ONTAP
* Pour les paires HA, l'instance médiateur Cloud Volumes ONTAP HA (si vous souhaitez déployer des paires HA)


.Étapes
. Accédez à la console IAM AWS et cliquez sur *Policies*.
. Créez une stratégie pour l'instance de connecteur.
+

NOTE: Vous créez ces règles pour prendre en charge les compartiments S3 dans votre environnement AWS. Lors de la création ultérieure des compartiments, assurez-vous que les noms des compartiments sont préfixés à l'aide de `fabric-pool-`. Cette exigence s'applique à la fois aux régions AWS Secret Cloud et Top Secret Cloud.

+
[role="tabbed-block"]
====
.Régions secrètes
--
[source, json]
----
{
    "Version": "2012-10-17",
    "Statement": [{
            "Effect": "Allow",
            "Action": [
                "ec2:DescribeInstances",
                "ec2:DescribeInstanceStatus",
                "ec2:RunInstances",
                "ec2:ModifyInstanceAttribute",
                "ec2:DescribeRouteTables",
                "ec2:DescribeImages",
                "ec2:CreateTags",
                "ec2:CreateVolume",
                "ec2:DescribeVolumes",
                "ec2:ModifyVolumeAttribute",
                "ec2:DeleteVolume",
                "ec2:CreateSecurityGroup",
                "ec2:DeleteSecurityGroup",
                "ec2:DescribeSecurityGroups",
                "ec2:RevokeSecurityGroupEgress",
                "ec2:RevokeSecurityGroupIngress",
                "ec2:AuthorizeSecurityGroupEgress",
                "ec2:AuthorizeSecurityGroupIngress",
                "ec2:CreateNetworkInterface",
                "ec2:DescribeNetworkInterfaces",
                "ec2:DeleteNetworkInterface",
                "ec2:ModifyNetworkInterfaceAttribute",
                "ec2:DescribeSubnets",
                "ec2:DescribeVpcs",
                "ec2:DescribeDhcpOptions",
                "ec2:CreateSnapshot",
                "ec2:DeleteSnapshot",
                "ec2:DescribeSnapshots",
                "ec2:GetConsoleOutput",
                "ec2:DescribeKeyPairs",
                "ec2:DescribeRegions",
                "ec2:DeleteTags",
                "ec2:DescribeTags",
                "cloudformation:CreateStack",
                "cloudformation:DeleteStack",
                "cloudformation:DescribeStacks",
                "cloudformation:DescribeStackEvents",
                "cloudformation:ValidateTemplate",
                "iam:PassRole",
                "iam:CreateRole",
                "iam:DeleteRole",
                "iam:PutRolePolicy",
                "iam:ListInstanceProfiles",
                "iam:CreateInstanceProfile",
                "iam:DeleteRolePolicy",
                "iam:AddRoleToInstanceProfile",
                "iam:RemoveRoleFromInstanceProfile",
                "iam:DeleteInstanceProfile",
                "s3:GetObject",
                "s3:ListBucket",
                "s3:GetBucketTagging",
                "s3:GetBucketLocation",
                "s3:ListAllMyBuckets",
                "kms:List*",
                "kms:Describe*",
                "ec2:AssociateIamInstanceProfile",
                "ec2:DescribeIamInstanceProfileAssociations",
                "ec2:DisassociateIamInstanceProfile",
                "ec2:DescribeInstanceAttribute",
                "ec2:CreatePlacementGroup",
                "ec2:DeletePlacementGroup"
            ],
            "Resource": "*"
        },
        {
            "Sid": "fabricPoolPolicy",
            "Effect": "Allow",
            "Action": [
                "s3:DeleteBucket",
                "s3:GetLifecycleConfiguration",
                "s3:PutLifecycleConfiguration",
                "s3:PutBucketTagging",
                "s3:ListBucketVersions"
            ],
            "Resource": [
                "arn:aws-iso-b:s3:::fabric-pool*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "ec2:StartInstances",
                "ec2:StopInstances",
                "ec2:TerminateInstances",
                "ec2:AttachVolume",
                "ec2:DetachVolume"
            ],
            "Condition": {
                "StringLike": {
                    "ec2:ResourceTag/WorkingEnvironment": "*"
                }
            },
            "Resource": [
                "arn:aws-iso-b:ec2:*:*:instance/*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "ec2:AttachVolume",
                "ec2:DetachVolume"
            ],
            "Resource": [
                "arn:aws-iso-b:ec2:*:*:volume/*"
            ]
        }
    ]
}
----
--
.Régions les plus secrètes
--
[source, json]
----
{
    "Version": "2012-10-17",
    "Statement": [{
            "Effect": "Allow",
            "Action": [
                "ec2:DescribeInstances",
                "ec2:DescribeInstanceStatus",
                "ec2:RunInstances",
                "ec2:ModifyInstanceAttribute",
                "ec2:DescribeRouteTables",
                "ec2:DescribeImages",
                "ec2:CreateTags",
                "ec2:CreateVolume",
                "ec2:DescribeVolumes",
                "ec2:ModifyVolumeAttribute",
                "ec2:DeleteVolume",
                "ec2:CreateSecurityGroup",
                "ec2:DeleteSecurityGroup",
                "ec2:DescribeSecurityGroups",
                "ec2:RevokeSecurityGroupEgress",
                "ec2:RevokeSecurityGroupIngress",
                "ec2:AuthorizeSecurityGroupEgress",
                "ec2:AuthorizeSecurityGroupIngress",
                "ec2:CreateNetworkInterface",
                "ec2:DescribeNetworkInterfaces",
                "ec2:DeleteNetworkInterface",
                "ec2:ModifyNetworkInterfaceAttribute",
                "ec2:DescribeSubnets",
                "ec2:DescribeVpcs",
                "ec2:DescribeDhcpOptions",
                "ec2:CreateSnapshot",
                "ec2:DeleteSnapshot",
                "ec2:DescribeSnapshots",
                "ec2:GetConsoleOutput",
                "ec2:DescribeKeyPairs",
                "ec2:DescribeRegions",
                "ec2:DeleteTags",
                "ec2:DescribeTags",
                "cloudformation:CreateStack",
                "cloudformation:DeleteStack",
                "cloudformation:DescribeStacks",
                "cloudformation:DescribeStackEvents",
                "cloudformation:ValidateTemplate",
                "iam:PassRole",
                "iam:CreateRole",
                "iam:DeleteRole",
                "iam:PutRolePolicy",
                "iam:ListInstanceProfiles",
                "iam:CreateInstanceProfile",
                "iam:DeleteRolePolicy",
                "iam:AddRoleToInstanceProfile",
                "iam:RemoveRoleFromInstanceProfile",
                "iam:DeleteInstanceProfile",
                "s3:GetObject",
                "s3:ListBucket",
                "s3:GetBucketTagging",
                "s3:GetBucketLocation",
                "s3:ListAllMyBuckets",
                "kms:List*",
                "kms:Describe*",
                "ec2:AssociateIamInstanceProfile",
                "ec2:DescribeIamInstanceProfileAssociations",
                "ec2:DisassociateIamInstanceProfile",
                "ec2:DescribeInstanceAttribute",
                "ec2:CreatePlacementGroup",
                "ec2:DeletePlacementGroup"
            ],
            "Resource": "*"
        },
        {
            "Sid": "fabricPoolPolicy",
            "Effect": "Allow",
            "Action": [
                "s3:DeleteBucket",
                "s3:GetLifecycleConfiguration",
                "s3:PutLifecycleConfiguration",
                "s3:PutBucketTagging",
                "s3:ListBucketVersions"
            ],
            "Resource": [
                "arn:aws-iso:s3:::fabric-pool*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "ec2:StartInstances",
                "ec2:StopInstances",
                "ec2:TerminateInstances",
                "ec2:AttachVolume",
                "ec2:DetachVolume"
            ],
            "Condition": {
                "StringLike": {
                    "ec2:ResourceTag/WorkingEnvironment": "*"
                }
            },
            "Resource": [
                "arn:aws-iso:ec2:*:*:instance/*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "ec2:AttachVolume",
                "ec2:DetachVolume"
            ],
            "Resource": [
                "arn:aws-iso:ec2:*:*:volume/*"
            ]
        }
    ]
}
----
--
====
. Création d'une policy pour Cloud Volumes ONTAP.
+
[role="tabbed-block"]
====
.Régions secrètes
--
[source, json]
----
{
    "Version": "2012-10-17",
    "Statement": [{
        "Action": "s3:ListAllMyBuckets",
        "Resource": "arn:aws-iso-b:s3:::*",
        "Effect": "Allow"
    }, {
        "Action": [
            "s3:ListBucket",
            "s3:GetBucketLocation"
        ],
        "Resource": "arn:aws-iso-b:s3:::fabric-pool-*",
        "Effect": "Allow"
    }, {
        "Action": [
            "s3:GetObject",
            "s3:PutObject",
            "s3:DeleteObject"
        ],
        "Resource": "arn:aws-iso-b:s3:::fabric-pool-*",
        "Effect": "Allow"
    }]
}
----
--
.Régions les plus secrètes
--
[source, json]
----
{
    "Version": "2012-10-17",
    "Statement": [{
        "Action": "s3:ListAllMyBuckets",
        "Resource": "arn:aws-iso:s3:::*",
        "Effect": "Allow"
    }, {
        "Action": [
            "s3:ListBucket",
            "s3:GetBucketLocation"
        ],
        "Resource": "arn:aws-iso:s3:::fabric-pool-*",
        "Effect": "Allow"
    }, {
        "Action": [
            "s3:GetObject",
            "s3:PutObject",
            "s3:DeleteObject"
        ],
        "Resource": "arn:aws-iso:s3:::fabric-pool-*",
        "Effect": "Allow"
    }]
}
----
--
====
+
Pour les paires HA, si vous prévoyez de déployer une paire Cloud Volumes ONTAP HA, créez une règle pour le médiateur HA.

+
[source, json]
----
{
	"Version": "2012-10-17",
	"Statement": [{
			"Effect": "Allow",
			"Action": [
				"ec2:AssignPrivateIpAddresses",
				"ec2:CreateRoute",
				"ec2:DeleteRoute",
				"ec2:DescribeNetworkInterfaces",
				"ec2:DescribeRouteTables",
				"ec2:DescribeVpcs",
				"ec2:ReplaceRoute",
				"ec2:UnassignPrivateIpAddresses"
			],
			"Resource": "*"
		}
	]
}
----
. Créez des rôles IAM avec le type de rôle Amazon EC2 et associez les règles créées aux étapes précédentes.
+
.Créer le rôle :
De la même manière que les règles, vous devez avoir un rôle IAM pour le connecteur et un pour les nœuds Cloud Volumes ONTAP.
Pour les paires HA : comme les règles, vous devez avoir un rôle IAM pour le connecteur, un pour les nœuds Cloud Volumes ONTAP et un pour le médiateur HA (si vous souhaitez déployer des paires HA).

+
.Sélectionnez le rôle :
Vous devez sélectionner le rôle IAM de connecteur lorsque vous lancez l'instance de connecteur. Vous pouvez sélectionner les rôles IAM pour Cloud Volumes ONTAP lorsque vous créez un environnement de travail Cloud Volumes ONTAP à partir de BlueXP.
Pour les paires HA, vous pouvez sélectionner les rôles IAM pour Cloud Volumes ONTAP et le médiateur HA lorsque vous créez un environnement de travail Cloud Volumes ONTAP à partir de BlueXP.





== Étape 3 : configuration du serveur KMS AWS

Si vous souhaitez utiliser le chiffrement Amazon avec Cloud Volumes ONTAP, vérifiez que les exigences du service de gestion des clés AWS (KMS) sont respectées.

.Étapes
. Assurez-vous qu'une clé maître client (CMK) active existe dans votre compte ou dans un autre compte AWS.
+
La CMK peut être une CMK gérée par AWS ou une CMK gérée par le client.

. Si le CMK se trouve dans un compte AWS séparé du compte sur lequel vous prévoyez de déployer Cloud Volumes ONTAP, vous devez obtenir l'ARN de cette clé.
+
Vous devrez fournir l'ARN à BlueXP lorsque vous créez le système Cloud Volumes ONTAP.

. Ajoutez le rôle IAM de l'instance de connecteur à la liste des utilisateurs clés d'un CMK.
+
Cela donne des autorisations BlueXP pour utiliser le CMK avec Cloud Volumes ONTAP.





== Étape 4 : installez le connecteur et configurez BlueXP

Avant de pouvoir commencer à utiliser BlueXP pour déployer Cloud Volumes ONTAP dans AWS, vous devez installer et configurer le connecteur BlueXP. BlueXP peut ainsi gérer les ressources et les processus au sein de votre environnement de cloud public (y compris Cloud Volumes ONTAP).

.Étapes
. Obtenir un certificat racine signé par une autorité de certification (CA) au format X.509 encodé base-64 de Privacy Enhanced Mail (PEM). Consultez les politiques et procédures de votre organisation pour obtenir le certificat.
+

NOTE: Pour les régions du cloud secret AWS, vous devez télécharger le `NSS Root CA 2` Et pour Top Secret Cloud, le `Amazon Root CA 4` certificat. Assurez-vous de télécharger uniquement ces certificats et non l'ensemble de la chaîne. Le fichier de la chaîne de certificats est volumineux et le téléchargement peut échouer. Si vous avez d'autres certificats, vous pouvez les télécharger ultérieurement, comme décrit à l'étape suivante.

+
Vous devrez télécharger le certificat pendant le processus d'installation. BlueXP utilise le certificat de confiance pour envoyer des demandes vers AWS via HTTPS.

. Lancez l'instance de connecteur :
+
.. Accédez à la page AWS Intelligence Community Marketplace pour BlueXP.
.. Dans l'onglet Custom Launch, sélectionnez l'option de lancement de l'instance à partir de la console EC2.
.. Suivez les invites pour configurer l'instance.
+
Notez les éléments suivants lors de la configuration de l'instance :

+
*** Nous recommandons une instance t3.XLarge.
*** Vous devez choisir le rôle IAM que vous avez créé lors de la configuration des autorisations.
*** Vous devez conserver les options de stockage par défaut.
*** Les méthodes de connexion requises pour le connecteur sont les suivantes : SSH, HTTP et HTTPS.




. Configurez BlueXP à partir d'un hôte qui a une connexion à l'instance de connecteur :
+
.. Ouvrez un navigateur Web et entrez https://_ipaddress_[] Où _ipaddress_ est l'adresse IP de l'hôte Linux où vous avez installé le connecteur.
.. Spécifiez un serveur proxy pour la connectivité aux services AWS.
.. Téléchargez le certificat que vous avez obtenu à l'étape 1.
.. Sélectionnez *configurer Nouveau BlueXP* et suivez les invites pour configurer le système.
+
*** *Détails du système* : saisissez un nom pour le connecteur et le nom de votre société.
*** *Créer un utilisateur Admin* : créez l'utilisateur admin pour le système.
+
Ce compte utilisateur s'exécute localement sur le système. Il n'y a pas de connexion au service auth0 disponible via BlueXP.

*** *Révision* : consultez les détails, acceptez le contrat de licence, puis sélectionnez *configurer*.


.. Pour terminer l'installation du certificat signé par l'autorité de certification, redémarrez l'instance de connecteur à partir de la console EC2.


. Une fois le connecteur redémarré, connectez-vous à l'aide du compte utilisateur administrateur que vous avez créé dans l'assistant de configuration.




== Étape 5 : (facultatif) installez un certificat en mode privé

Cette étape est facultative pour les régions Cloud secret AWS et Cloud secret principal, et n'est requise que si vous avez des certificats supplémentaires, à l'exception des certificats racine que vous avez installés à l'étape précédente.

.Étapes
. Répertorie les certificats installés existants.
+
.. Pour collecter l'ID docker du conteneur ocm (nommé « ds-octm-1 »), exécutez la commande suivante :
+
[source, CLI]
----
docker ps
----
.. Pour accéder à l'intérieur du conteneur octm, exécutez la commande suivante :
+
[source, CLI]
----
docker exec -it <docker-id> /bin/sh
----
.. Pour collecter le mot de passe à partir de la variable d'environnement « TRUST_STORE_PASSWORD », exécutez la commande suivante :
+
[source, CLI]
----
env
----
.. Pour répertorier tous les certificats installés dans truststore, exécutez la commande suivante et utilisez le mot de passe collecté à l'étape précédente :
+
[source, CLI]
----
keytool -list -v -keystore occm.truststore
----


. Ajouter un certificat.
+
.. Pour collecter l'ID docker du conteneur ocm (nommé « ds-octm-1 »), exécutez la commande suivante :
+
[source, CLI]
----
docker ps
----
.. Pour accéder à l'intérieur du conteneur octm, exécutez la commande suivante :
+
[source, CLI]
----
docker exec -it <docker-id> /bin/sh
----
+
Enregistrez le nouveau fichier de certificat à l'intérieur.

.. Pour collecter le mot de passe à partir de la variable d'environnement « TRUST_STORE_PASSWORD », exécutez la commande suivante :
+
[source, CLI]
----
env
----
.. Pour ajouter le certificat au magasin de confiance, exécutez la commande suivante et utilisez le mot de passe de l'étape précédente :
+
[source, CLI]
----
keytool -import -alias <alias-name> -file <certificate-file-name> -keystore occm.truststore
----
.. Pour vérifier que le certificat est installé, exécutez la commande suivante :
+
[source, CLI]
----
keytool -list -v -keystore occm.truststore -alias <alias-name>
----
.. Pour quitter le conteneur octm, exécutez la commande suivante :
+
[source, CLI]
----
exit
----
.. Pour réinitialiser le conteneur octm, exécutez la commande suivante :
+
[source, CLI]
----
docker restart <docker-id>
----




--

--


== Étape 6 : ajoutez une licence au portefeuille digital BlueXP

Si vous avez acheté une licence auprès de NetApp, vous devez l'ajouter au portefeuille digital BlueXP afin de sélectionner la licence lors de la création d'un nouveau système Cloud Volumes ONTAP. Le portefeuille numérique identifie ces licences comme non attribuées.

.Étapes
. Dans le menu de navigation BlueXP, sélectionnez *gouvernance > porte-monnaie numérique*.
. Dans l'onglet *Cloud Volumes ONTAP*, sélectionnez *licences par nœud* dans la liste déroulante.
. Cliquez sur *non affecté*.
. Cliquez sur *Ajouter des licences non attribuées*.
. Saisissez le numéro de série de la licence ou téléchargez le fichier de licence.
. Si vous n'avez pas encore le fichier de licence, vous devrez télécharger manuellement le fichier de licence à partir de netapp.com.
+
.. Accédez au link:https://register.netapp.com/site/vsnr/register/getlicensefile["Générateur de fichiers de licences NetApp"^] Et connectez-vous en utilisant vos identifiants du site du support NetApp.
.. Entrez votre mot de passe, choisissez votre produit, entrez le numéro de série, confirmez que vous avez lu et accepté la politique de confidentialité, puis cliquez sur *Envoyer*.
.. Choisissez si vous souhaitez recevoir le fichier numéro de série.NLF JSON par e-mail ou par téléchargement direct.


. Cliquez sur *Ajouter une licence*.


.Résultat
BlueXP ajoute la licence au portefeuille digital. La licence sera identifiée comme non affectée jusqu'à ce que vous l'associez à un nouveau système Cloud Volumes ONTAP. À ce stade, la licence est déplacée vers l'onglet BYOL du portefeuille digital.



== Étape 7 : lancez Cloud Volumes ONTAP à partir de BlueXP

Vous pouvez lancer des instances Cloud Volumes ONTAP dans le cloud secret AWS et le cloud secret en créant de nouveaux environnements de travail dans BlueXP.

.Avant de commencer
Pour les paires HA, une paire de clés est requise pour activer l'authentification SSH basée sur des clés au médiateur HA.

.Étapes
. Sur la page environnements de travail, cliquez sur *Ajouter un environnement de travail*.
. Sous *Créer*, sélectionnez Cloud Volumes ONTAP.
+
Pour HA : sous *Créer*, sélectionnez Cloud Volumes ONTAP ou Cloud Volumes ONTAP HA.

. Suivez les étapes de l'assistant pour lancer le système Cloud Volumes ONTAP.
+

CAUTION: Lors de la sélection à l'aide de l'assistant, ne sélectionnez pas *Data Sense & Compliance* et *Backup to Cloud* sous *Services*. Sous *Packages préconfigurés*, sélectionnez *Modifier la configuration* uniquement et assurez-vous que vous n'avez sélectionné aucune autre option. Les packages préconfigurés ne sont pas pris en charge dans les régions AWS Secret Cloud et Top Secret Cloud, et si cette option est sélectionnée, votre déploiement échouera.



.Remarques sur le déploiement de Cloud Volumes ONTAP HA dans plusieurs zones de disponibilité
Notez les points suivants lorsque vous terminez l'assistant pour les paires haute disponibilité.

* Vous devez configurer une passerelle de transit lorsque vous déployez Cloud Volumes ONTAP HA dans plusieurs zones de disponibilité (AZ). Pour obtenir des instructions, reportez-vous à link:task-setting-up-transit-gateway.html["Configuration d'une passerelle de transit AWS"]la .
* Déployez la configuration comme suit car seulement deux zones de disponibilité étaient disponibles dans le Top Secret Cloud d'AWS au moment de la publication :
+
** Nœud 1 : zone de disponibilité A
** Nœud 2 : zone de disponibilité B
** Médiateur : zone de disponibilité A ou B




.Remarques sur le déploiement de Cloud Volumes ONTAP dans un nœud unique ou haute disponibilité
Notez les éléments suivants lorsque vous terminez l'assistant :

* Vous devez laisser l'option par défaut pour utiliser un groupe de sécurité généré.
+
Le groupe de sécurité prédéfini comprend les règles dont Cloud Volumes ONTAP a besoin pour fonctionner correctement. Si vous avez besoin d'utiliser votre propre, vous pouvez vous reporter à la section du groupe de sécurité ci-dessous.

* Vous devez choisir le rôle IAM que vous avez créé lors de la préparation de votre environnement AWS.
* Le type de disque AWS sous-jacent concerne le volume Cloud Volumes ONTAP initial.
+
Vous pouvez choisir un autre type de disque pour les volumes suivants.

* Les performances des disques AWS sont liées à leur taille.
+
Choisissez la taille qui offre les performances dont vous avez besoin. Pour plus d'informations sur les performances d'EBS, consultez la documentation AWS.

* La taille du disque est la taille par défaut de tous les disques du système.
+

NOTE: Si vous avez besoin d'une taille différente par la suite, vous pouvez utiliser l'option d'allocation avancée pour créer un agrégat qui utilise des disques d'une taille spécifique.



.Résultat
BlueXP lance l'instance Cloud Volumes ONTAP. Vous pouvez suivre la progression dans la chronologie.



== Étape 8 : installez les certificats de sécurité pour la hiérarchisation des données

Vous devez installer manuellement des certificats de sécurité pour activer le Tiering des données dans les régions AWS Secret Cloud et Top Secret Cloud.

.Avant de commencer
. Création de compartiments S3.
+

NOTE: Assurez-vous que les noms de compartiment sont préfixés par `fabric-pool-.` Par exemple `fabric-pool-testbucket`.

. Conservez les certificats racine que vous avez installés dans `step 4` pratique.


.Étapes
. Copiez le texte des certificats racine que vous avez installés dans `step 4`.
. Connexion sécurisée au système Cloud Volumes ONTAP via l'interface de ligne de commande.
. Installez les certificats racine. Vous devrez peut-être appuyer sur `ENTER` saisir plusieurs fois :
+
[listing]
----
security certificate install -type server-ca -cert-name <certificate-name>
----
. Lorsque vous y êtes invité, entrez le texte intégralement copié, y compris et de `----- BEGIN CERTIFICATE -----` à `----- END CERTIFICATE -----`.
. Conservez une copie du certificat numérique signé par l'autorité de certification pour référence ultérieure.
. Conservez le nom de l'autorité de certification et le numéro de série du certificat.
. Configurez le magasin d'objets pour les régions AWS Secret Cloud et Top Secret Cloud : `set -privilege advanced -confirmations off`
. Exécutez cette commande pour configurer le magasin d'objets.
+

NOTE: Tous les noms de ressources Amazon (ARN) doivent être accompagnés du suffixe `-iso-b`, comme `arn:aws-iso-b`. Par exemple, si une ressource requiert un ARN avec une région, pour Top Secret Cloud, utilisez la convention de dénomination comme `us-iso-b` pour le `-server` drapeau. Pour le cloud secret AWS, utilisez `us-iso-b-1`.

+
[listing]
----
storage aggregate object-store config create -object-store-name <S3Bucket> -provider-type AWS_S3 -auth-type EC2-IAM -server <s3.us-iso-b-1.server_name> -container-name <fabric-pool-testbucket> -is-ssl-enabled true -port 443
----
. Vérifiez que le magasin d'objets a été créé avec succès : `storage aggregate object-store show -instance`
. Reliez le magasin d'objets à l'agrégat. Cette opération doit être répétée pour chaque nouvel agrégat : `storage aggregate object-store attach -aggregate <aggr1> -object-store-name <S3Bucket>`

