---
sidebar: sidebar 
permalink: task-managing-svms-gcp.html 
keywords: storage virtual machine, vserver, svm, storage vm, supported number, number supported, create svm, create storage vm, create vserver 
summary: Une VM de stockage est une machine virtuelle exécutée dans ONTAP, qui fournit des services de données et de stockage à vos clients. On peut le connaître comme un SVM ou un vserver. La solution Cloud Volumes ONTAP est configurée par défaut avec une seule machine virtuelle de stockage, mais certaines configurations prennent en charge des machines virtuelles de stockage supplémentaires. 
---
= Gestion des machines virtuelles de stockage destinées à la transmission des données pour Cloud Volumes ONTAP dans Google Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Une VM de stockage est une machine virtuelle exécutée dans ONTAP, qui fournit des services de données et de stockage à vos clients. Vous pouvez le connaître comme _SVM_ ou _vserver_. La solution Cloud Volumes ONTAP est configurée par défaut avec une seule machine virtuelle de stockage, mais certaines configurations prennent en charge des machines virtuelles de stockage supplémentaires.

Pour créer et gérer des machines virtuelles de stockage supplémentaires qui servent les données dans Google Cloud, vous devez utiliser les API BlueXP . En effet, ces API automatisent le processus de création des machines virtuelles de stockage et de configuration des interfaces réseau requises. Lors de la création des machines virtuelles de stockage, BlueXP  configure les services LIF requis, ainsi qu'une LIF iSCSI requise pour les communications SMB/CIFS sortantes depuis la machine virtuelle de stockage.

Pour plus d'informations sur l'exécution des appels de l'API Cloud Volumes ONTAP, reportez-vous https://docs.netapp.com/us-en/bluexp-automation/cm/your_api_call.html#step-1-select-the-identifie["Votre premier appel API"^] à la section .



== Nombre de machines virtuelles de stockage pris en charge

À partir de Cloud Volumes ONTAP 9.11.1, selon votre licence, plusieurs machines virtuelles de stockage sont prises en charge avec des configurations spécifiques. Reportez-vous https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/index.html["Notes de version de Cloud Volumes ONTAP"^] au pour vérifier le nombre de machines virtuelles de stockage prises en charge pour votre version de Cloud Volumes ONTAP.

Toutes les versions de Cloud Volumes ONTAP antérieures à la version 9.11.1 prennent en charge une VM de stockage servant les données et une VM de stockage de destination utilisée pour la reprise après incident. Vous pouvez activer la machine virtuelle de stockage de destination pour accéder aux données en cas de panne sur la machine virtuelle de stockage source.



== Créez une machine virtuelle de stockage

En fonction de votre configuration et de votre type de licence, vous pouvez créer plusieurs machines virtuelles de stockage sur un système à un seul nœud ou dans une configuration haute disponibilité à l'aide des API BlueXP .

.Description de la tâche
Lorsque vous créez des machines virtuelles de stockage à l'aide des API et que vous configurez les interfaces réseau requises, BlueXP  modifie également les `default-data-files` règles sur les machines virtuelles de stockage de données en supprimant les services suivants de la LIF de données NAS et en les ajoutant à la LIF de données iSCSI utilisée pour les connexions de gestion sortantes :

* `data-fpolicy-client`
* `management-ad-client`
* `management-dns-client`
* `management-ldap-client`
* `management-nis-client`


.Avant de commencer
Le connecteur nécessite des autorisations spécifiques pour créer des VM de stockage pour les paires haute disponibilité Cloud Volumes ONTAP. Les autorisations requises sont incluses dans https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions-gcp.html["Règles fournies par NetApp"^].



=== Système à un seul nœud

Utilisez l'appel d'API suivant pour créer une VM de stockage sur un système à un seul nœud.

`POST /gcp/vsa/working-environments/{workingEnvironmentId}/svm`

Inclure les paramètres suivants dans le corps de la demande :

[source, json]
----
{ "svmName": "NewSvmName"
   "svmPassword": "optional value, the API takes the cluster password if not provided"
   "mgmtLif": "optional value, to create an additional management LIF, if you want to use the storage VM for management purposes"}
----


=== Paire HA

Utilisez l'appel d'API suivant pour créer une VM de stockage sur une paire HA :

`POST /gcp/ha/working-environments/{workingEnvironmentId}/svm/`

Inclure les paramètres suivants dans le corps de la demande :

[source, json]
----
{ "svmName": "NewSvmName"
   "svmPassword": "optional value, the API takes the cluster password if not provided"
}
----


== Gérer les machines virtuelles de stockage

Grâce aux API BlueXP , vous pouvez renommer et supprimer des machines virtuelles de stockage dans des configurations haute disponibilité à un seul nœud.

.Avant de commencer
Le connecteur nécessite des autorisations spécifiques pour gérer les VM de stockage pour les paires haute disponibilité Cloud Volumes ONTAP. Les autorisations requises sont incluses dans https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions-gcp.html["Règles fournies par NetApp"^].



=== Renommer une machine virtuelle de stockage

Pour renommer une machine virtuelle de stockage, indiquez les noms de la machine virtuelle de stockage existante et de la nouvelle machine virtuelle de stockage en tant que paramètres.

.Étapes
* Utilisez l'appel d'API suivant pour renommer une VM de stockage sur un système à un seul nœud :
+
`PUT /gcp/vsa/working-environments/{workingEnvironmentId}/svm`

+
Inclure les paramètres suivants dans le corps de la demande :

+
[source, json]
----
{
  "svmNewName": "NewSvmName",
  "svmName": "OldSvmName"
}
----
* Utilisez l'appel d'API suivant pour renommer une VM de stockage sur une paire HA :
+
`PUT /gcp/ha/working-environments/{workingEnvironmentId}/svm`

+
Inclure les paramètres suivants dans le corps de la demande :

+
[source, json]
----
{
  "svmNewName": "NewSvmName",
  "svmName": "OldSvmName"
}
----




=== Supprimer une machine virtuelle de stockage

Dans une configuration à un seul nœud ou haute disponibilité, vous pouvez supprimer une VM de stockage s'il ne possède aucun volume actif.

.Étapes
* Utilisez l'appel d'API suivant pour supprimer une VM de stockage sur un système à un seul nœud :
+
`DELETE /gcp/vsa/working-environments/{workingEnvironmentId}/svm/{svmName}`

* Utilisez l'appel d'API suivant pour supprimer une VM de stockage sur une paire HA :
+
`DELETE /gcp/ha/working-environments/{workingEnvironmentId}/svm/{svmName}`



.Informations associées
* https://docs.netapp.com/us-en/bluexp-automation/cm/prepare.html["Préparez-vous à utiliser l'API"^]
* https://docs.netapp.com/us-en/bluexp-automation/cm/workflow_processes.html#organization-of-cloud-volumes-ontap-workflows["Workflows Cloud Volumes ONTAP"^]
* https://docs.netapp.com/us-en/bluexp-automation/platform/get_identifiers.html#get-the-connector-identifier["Obtenir les identifiants requis"^]
* https://docs.netapp.com/us-en/bluexp-automation/platform/use_rest_apis.html["Utiliser les API REST BlueXP"^]

