---
sidebar: sidebar 
permalink: task-configure-placement-group-failure-aws.html 
keywords: placement group, failure, HA single zone, app.conf, rollback, AWS 
summary: Cloud Volumes ONTAP utilise une liaison privée Azure pour les connexions aux comptes de stockage associés. Si nécessaire, vous pouvez désactiver les liens privés Azure et utiliser les terminaux de service. 
---
= Configurez la création de groupes de placement pour les paires HA Cloud Volumes ONTAP dans les zones de disponibilité AWS individuelles
:allow-uri-read: 


[role="lead"]
Les déploiements Cloud Volumes ONTAP haute disponibilité dans une zone de disponibilité unique AWS peuvent échouer et revenir en arrière en cas de défaillance de la création du groupe de placement. La création du groupe de placement échoue également et le déploiement revient en arrière si le nœud Cloud Volumes ONTAP et l'instance du médiateur ne sont pas disponibles. Pour éviter cela, vous pouvez modifier la configuration pour permettre la fin du déploiement, même si la création du groupe de positionnement échoue.

Si vous contournez le processus de restauration, le processus de déploiement Cloud Volumes ONTAP s'achève avec succès et vous informe que la création du groupe de placement est incomplète.

.Étapes
. Utilisez SSH pour vous connecter à l'hôte du connecteur et connectez-vous.
. Accédez à `/opt/application/netapp/cloudmanager/docker_occm/data`.
. Modifiez `app.conf` en changeant la valeur du `rollback-on-placement-group-failure` paramètre à `false`. La valeur par défaut de ce paramètre est `true`.
+
[listing]
----
{
    "occm" : {
        "aws" : {
            "rollback-on-placement-group-failure" : false
        }
    }
}
----
. Enregistrez le fichier et déconnectez le connecteur. Vous n'avez pas besoin de redémarrer le connecteur.

