---
sidebar: sidebar 
permalink: task-manage-svm-dr.html 
keywords: storage virtual machine, vserver, svm, storage vm, svm dr, disaster recovery, svm disaster recovery, storage vm dr 
summary: 'BlueXP ne propose pas de prise en charge de la configuration ou de l"orchestration pour la reprise après incident des machines virtuelles de stockage. Vous devez utiliser System Manager ou l"interface de ligne de commandes.' 
---
= Configurez la reprise après incident de la machine virtuelle de stockage pour Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP n'offre pas de support de configuration ou d'orchestration pour la reprise après sinistre des machines virtuelles de stockage (SVM). Pour effectuer ces tâches, utilisez ONTAP System Manager ou l'interface de ligne de commande ONTAP.

Si vous configurez la réplication SnapMirror SVM entre deux systèmes Cloud Volumes ONTAP, la réplication doit se faire entre deux systèmes de paire HA ou deux systèmes à un seul nœud. Il n'est pas possible de configurer la réplication SnapMirror SVM entre une paire haute disponibilité et un système à un seul nœud.

Pour obtenir des instructions sur l'interface de ligne de commandes de ONTAP, reportez-vous aux documents suivants.

* https://library.netapp.com/ecm/ecm_get_file/ECMLP2839856["Guide de préparation rapide pour la reprise après incident du SVM"^]
* https://library.netapp.com/ecm/ecm_get_file/ECMLP2839857["Guide de reprise après incident de SVM Express"^]

