---
sidebar: sidebar 
permalink: task-deploy-cvo-azure-mktplc.html 
keywords: deploy cvo marketplace, marketplace direct cvo deployment, azure marketplace 
summary:  
---
= Déployez Cloud Volumes ONTAP à partir d'Azure Marketplace
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez utiliser le déploiement direct d'Azure Marketplace pour déployer rapidement et facilement Cloud Volumes ONTAP. À partir d'Azure Marketplace, vous pouvez déployer rapidement Cloud Volumes ONTAP en quelques clics et explorer ses principales fonctionnalités dans votre environnement.

Pour plus d'informations sur cette offre, reportez-vous à link:concept-azure-mktplace-direct.html["Découvrez les offres Cloud Volumes ONTAP sur BlueXP  et sur le marché"].

.Description de la tâche
Le système Cloud Volumes ONTAP déployé à l'aide d'Azure Marketplace Direct Deployment possède ces propriétés. Notez que les fonctionnalités d'une instance autonome déployée via Azure Marketplace changent lors de la découverte dans BlueXP .

* La dernière version de Cloud Volumes ONTAP (9.16.1 ou ultérieure).
* Une licence gratuite pour Cloud Volumes ONTAP limitée à 500 Gio de capacité provisionnée Cette licence ne prend pas en charge NetApp et n'a pas de date d'expiration.
* Deux nœuds configurés en mode haute disponibilité (HA) dans une zone de disponibilité unique (AZ), provisionnés avec des numéros de série par défaut. Les machines virtuelles de stockage (machines virtuelles de stockage) sont déployées dans un link:concept-ha-azure.html#ha-single-availability-zone-configuration-with-shared-managed-disks["mode d'orchestration flexible"].
* Un agrégat pour l'instance créée par défaut.
* Un disque géré Premium SSD v2 de 500 Gio de capacité provisionnée, ainsi qu'une racine et un disque de données.
* Une VM de stockage de données déployée, avec les services de données NFS, CIFS, iSCSI et NVMe/TCP. Vous ne pouvez pas ajouter de machines virtuelles de stockage de données supplémentaires.
* Licences installées pour NFS, CIFS (SMB), iSCSI, la protection anti-ransomware autonome (ARP), SnapLock et SnapMirror.
* https://docs.netapp.com/us-en/ontap/volumes/enable-temperature-sensitive-efficiency-concept.html["Efficacité du stockage ONTAP sensible à la température (TSSE)"^], le chiffrement de volume et la gestion externe des clés sont activés par défaut.
* Ces fonctionnalités ne sont pas prises en charge :
+
** Hiérarchisation FabricPool
** Modification du type de VM de stockage
** Mode d'écriture rapide




.Avant de commencer
* Assurez-vous de disposer d'un abonnement Azure Marketplace valide.
* Assurez-vous de répondre aux exigences de mise en réseau pour un link:concept-ha-azure.html#ha-single-availability-zone-configuration-with-shared-managed-disks["Déploiement HAUTE DISPONIBILITÉ dans une zone de DISPONIBILITÉ unique"] dans Azure. Reportez-vous à la link:reference-networking-azure.html["Configuration du réseau Azure pour Cloud Volumes ONTAP"].
* Pour déployer Cloud Volumes ONTAP, vous devez attribuer l'un des rôles Azure suivants :
+
**  `contributor`Rôle avec les autorisations par défaut. Pour plus d'informations, reportez-vous au https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles["Documentation Azure : rôles intégrés à Azure"^].
** Rôle RBAC personnalisé avec les autorisations suivantes. Pour plus d'informations, reportez-vous au https://learn.microsoft.com/en-us/azure/role-based-access-control/custom-roles["Documentation Azure : rôles personnalisés Azure"^].
+
[]
====
« Autorisations » : [ { « actions » : [ « Microsoft.AAD/register/action », « Microsoft.Resources/souscriptions/resourceGroups/Microsoft.Compute/capacityReservationGroups/deploy/action" write », « Microsoft.Network/loadBalancers/write" Microsoft.Network/networkInterfaces/write" Microsoft.Compute/virtualMachines/write" Microsoft.Compute/virtualMachines/extensions/write" Microsoft.Network/virtualNetworks/read" Microsoft.Compute/disks/write" Microsoft.Network/virtualNetworks/subnets/write", « Microsoft.ClassicCompute/virtualMachines/Microsoft.Network/virtualNetworks/write" write » Microsoft.Network/networkSecurityGroups/write" Microsoft.Network/networkSecurityGroups/read" Microsoft.Compute/virtualMachineScaleSets/write" Microsoft.Network/virtualNetworks/subnets/read"

====
+

NOTE: Si vous avez enregistré le fournisseur de ressources « Microsoft.Storage » dans votre abonnement, vous n'avez pas besoin de cette `Microsoft.AAD/register/action` autorisation. Pour plus d'informations, reportez-vous au https://learn.microsoft.com/en-us/azure/role-based-access-control/permissions/storage["Documentation Azure : autorisations Azure pour le stockage"^].





.Étapes
. Sur le site Azure Marketplace, recherchez les produits NetApp.
. Sélectionnez *NetApp Cloud Volumes ONTAP direct*.
. Cliquez sur *Create* pour lancer l'assistant de déploiement.
. Sélectionnez un plan. La liste *Plan* affiche généralement les dernières versions de Cloud Volumes ONTAP.
. Dans l'onglet *Notions de base*, fournissez les détails suivants :
+
** *Abonnement* : sélectionnez un abonnement. Le déploiement sera lié au numéro d'abonnement.
** *Groupe de ressources* : utilisez un groupe de ressources existant ou créez-en un nouveau. Les groupes de ressources permettent d'allouer toutes les ressources, telles que les disques et les machines virtuelles de stockage, au sein d'un même groupe pour un système Cloud Volumes ONTAP.
** *Région* : sélectionnez une région qui prend en charge le déploiement d'Azure HA dans une zone de disponibilité unique. Vous ne voyez que les régions disponibles dans la liste.
** *Taille* : sélectionnez une taille de VM de stockage pour le disque géré Premium SSD v2 pris en charge.
** *Zone* : sélectionnez une zone pour la région que vous avez sélectionnée.
** *Mot de passe Admin* : définissez un mot de passe. Vous utilisez ce mot de passe d'administration pour vous connecter au système après le déploiement.
** *Confirmer le mot de passe* : saisissez à nouveau le même mot de passe pour confirmation.
+
*** Dans l'onglet *réseau*, ajoutez un réseau virtuel et un sous-réseau, ou sélectionnez-les dans les listes.
+

NOTE: Pour respecter les restrictions de Microsoft Azure, vous devez créer un nouveau sous-réseau lors de la configuration d'un nouveau réseau virtuel. De même, si vous choisissez un réseau existant, vous devez sélectionner un sous-réseau existant.

*** Pour sélectionner un groupe de sécurité réseau prédéfini, sélectionnez *Oui*. Sélectionnez *non* pour attribuer un groupe de sécurité réseau Azure prédéfini avec les règles de trafic nécessaires. Pour plus d'informations, reportez-vous link:reference-networking-azure.html#security-group-rules["Règles de groupe de sécurité pour Azure"]à .
*** Dans l'onglet *Avancé*, vérifiez si les deux fonctionnalités Azure nécessaires à ce déploiement ont été définies. Reportez-vous à link:task-saz-feature.html["Activez une fonctionnalité Azure pour les déploiements Cloud Volumes ONTAP dans une zone de disponibilité unique"]et link:task-azure-high-availability-mode.html["Activez le mode haute disponibilité pour Cloud Volumes ONTAP dans Azure"].
*** Vous pouvez définir des paires nom et valeur pour les ressources ou les groupes de ressources dans l'onglet *Tags*.
*** Dans l'onglet *consulter + créer*, passez en revue les détails et démarrez le déploiement.






.Une fois que vous avez terminé
Sélectionnez l'icône de notification pour afficher la progression de votre déploiement. Une fois Cloud Volumes ONTAP déployé, vous pouvez afficher la VM de stockage répertoriée pour les opérations.

Une fois accessible, utilisez ONTAP System Manager ou l'interface de ligne de commandes ONTAP pour vous connecter à la machine virtuelle de stockage avec les informations d'identification d'administration que vous avez définies. Par la suite, vous pouvez créer des volumes, des LUN ou des partages et commencer à utiliser les fonctionnalités de stockage de Cloud Volumes ONTAP.



== Résoudre les problèmes de déploiement

Les systèmes Cloud Volumes ONTAP déployés directement via Azure Marketplace n'incluent pas le support d'NetApp. Vous pouvez identifier et résoudre les problèmes éventuels pendant le déploiement de manière indépendante.

.Étapes
. Sur le site Azure Marketplace, accédez à *Boot diagnostics > Serial log*.
. Téléchargez et examinez les journaux série.
. Consultez la documentation du produit et les articles de la base de connaissances pour obtenir des informations sur le dépannage.
+
** https://learn.microsoft.com/en-us/partner-center/["Documentation d'Azure Marketplace"]
** https://www.netapp.com/support-and-training/documentation/["Documentation NetApp"]
** https://kb.netapp.com/["Articles de la base de connaissances NetApp"]






== Découvrez les systèmes déployés dans BlueXP 

Vous pouvez découvrir les systèmes Cloud Volumes ONTAP que vous avez déployés à l'aide d'Azure Marketplace, leur déploiement direct et les gérer en tant qu'environnements de travail dans BlueXP . BlueXP  Connector détecte les systèmes, les ajoute en tant qu'environnements de travail, applique les licences BlueXP  nécessaires et libère toutes les capacités de BlueXP  pour ces systèmes. La configuration haute disponibilité d'origine dans une zone de disponibilité unique avec des disques gérés PSSD v2 est conservée et le système est enregistré dans les mêmes abonnement Azure et groupe de ressources que le déploiement d'origine.

.Description de la tâche
Après avoir découvert les systèmes Cloud Volumes ONTAP déployés à l'aide d'un déploiement direct Azure Marketplace, BlueXP  Connector effectue les tâches suivantes :

* Remplace les licences gratuites des systèmes découverts en tant que licences régulières basées sur la capacité link:concept-licensing.html#packages["Licences Freemium"].
* Conserve les fonctionnalités existantes des systèmes déployés et ajoute les fonctionnalités supplémentaires de BlueXP , telles que la protection des données, la gestion des données et les fonctions de sécurité.
* Remplace les licences installées sur les nœuds par de nouvelles licences ONTAP pour NFS, CIFS (SMB), iSCSI, ARP, SnapLock et SnapMirror.
* Convertit les numéros de série des nœuds génériques en numéros de série uniques.
* Attribue de nouveaux balises système aux ressources, le cas échéant.
* Convertit les adresses IP dynamiques de l'instance en adresses IP statiques.
* Active les fonctionnalités du stockagelink:task-tiering.html["Hiérarchisation FabricPool"] , link:task-verify-autosupport.html["AutoSupport"]et link:concept-worm.html["write-once-read-many"] (WORM) sur les systèmes déployés. Vous pouvez activer ces fonctionnalités à partir de la console BlueXP  lorsque vous en avez besoin.
* Enregistre les instances dans les comptes NSS utilisés pour les découvrir.
* Active des fonctionnalités de gestion de la capacité dans link:concept-storage-management.html#capacity-management["modes automatique et manuel"] pour les systèmes détectés.


.Avant de commencer
Vérifiez que le déploiement est complet sur Azure Marketplace. BlueXP  Connector ne peut détecter les systèmes qu'une fois le déploiement terminé et qu'il est disponible pour la découverte.

.Étapes
Dans BlueXP , vous suivez la procédure standard pour détecter les systèmes existants. Reportez-vous à la link:task-adding-systems.html["Ajouter un système Cloud Volumes ONTAP existant à BlueXP "].

.Une fois que vous avez terminé
Une fois la détection terminée, vous pouvez afficher les systèmes répertoriés en tant qu'environnements de travail dans BlueXP . Vous pouvez effectuer diverses tâches de gestion, telles que link:task-manage-aggregates.html["extension de l'agrégat"], , link:task-create-volumes.html["ajout de volumes"] link:task-managing-svms-azure.html["Provisionnement d'ordinateurs virtuels de stockage supplémentaires"]et link:task-change-azure-vm.html["modification des types d'instances"].

.Liens connexes
Pour plus d'informations sur la création de stockage, reportez-vous à la documentation ONTAP :

* https://docs.netapp.com/us-en/ontap/volumes/create-volume-task.html["Création de volumes pour NFS"^]
* https://docs.netapp.com/us-en/ontap-cli/lun-create.html["Créer des LUN pour iSCSI"^]
* https://docs.netapp.com/us-en/ontap-cli/vserver-cifs-share-create.html["Créez des partages pour CIFS"^]

