= Authentification utilisateur activée pour l'accès à System Manager depuis BlueXP 
:allow-uri-read: 




=== Authentification utilisateur activée pour l'accès à System Manager depuis BlueXP 

En tant qu'administrateur BlueXP , vous pouvez désormais activer l'authentification des utilisateurs ONTAP qui accèdent à ONTAP System Manager depuis BlueXP . Vous pouvez activer cette option en modifiant les paramètres du connecteur BlueXP . Cette option est disponible pour les modes standard et privé.

link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-administer-advanced-view.html["Administrez Cloud Volumes ONTAP à l'aide de System Manager"^].



=== La vue avancée de BlueXP  a été renommée Gestionnaire système

L'option de gestion avancée de Cloud Volumes ONTAP de BlueXP  à ONTAP System Manager a été renommée de *vue avancée* en *Gestionnaire système*.

link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-administer-advanced-view.html["Administrez Cloud Volumes ONTAP à l'aide de System Manager"^].



=== Découvrez un moyen plus simple de gérer les licences avec le portefeuille digital BlueXP 

La gestion des licences Cloud Volumes ONTAP est simplifiée grâce à des points de navigation améliorés dans le portefeuille digital BlueXP  :

* Accédez facilement aux informations relatives à votre licence Cloud Volumes ONTAP via les onglets *gouvernance > portefeuille numérique > Présentation/licences directes*.
* Cliquez sur *Afficher* dans le panneau ONTAP de volume cloud de l'onglet *Présentation* pour obtenir une compréhension complète de vos licences basées sur la capacité. Cette vue avancée offre des informations détaillées sur vos licences et vos abonnements.
* Si vous préférez l'interface précédente, vous pouvez cliquer sur le bouton *basculer vers la vue héritée* pour afficher les détails de la licence par type et modifier les méthodes de facturation de vos licences.


link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-manage-capacity-licenses.html["Gestion des licences basées sur la capacité"^].
